server:
  port: 8088

spring:
  datasource:
    username: tangxin
    password: 123456
    url: jdbc:mysql://localhost:3306/jiaocai?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
      ##xml文件的路径配置
  mapper-locations:  classpath:mapper/*.xml




